version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: technicall_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: technicall
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysqldata:
